swagger: '2.0'
info:
  description: |
    CodeGorilla week 2: PHP/API exercise
  version: 1.0.0
  title: week 2 chat backend

paths:

  /api.php:
    get:
      tags:
      - Message
      summary: Get messages
      produces:
      - application/json
      parameters:
      - in: query
        name: mykey
        type: string
        required: true
      responses:
        200:
          description: Operation successful
          schema:
            type: string
            items:
              $ref: '#/definitions/Message'
        400:
          description: Operation failed

    post:
      tags:
      - Message
      summary: Create message
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/Message'
      responses:
        200:
          description: Operation successful, returns new id
          schema:
            type: integer
        400:
          description: Operation failed

#############################################################################
# Objects
#############################################################################

definitions:
  Message:
    type: object
    properties:
      mykey:
        type: string
      value:
        type: string